name: Task
description: Create a development task
title: "[TASK] "
labels: ["task"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Use this template for development tasks and implementation work.

  - type: input
    id: title
    attributes:
      label: Task Title
      description: Brief, descriptive title
      placeholder: "Implement X system"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed description of what needs to be done
      placeholder: "This task involves..."
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What needs to be completed for this task to be done?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What component does this relate to?
      options:
        - Core Engine
        - Character System
        - Combat
        - Animation
        - Physics
        - Graphics
        - Audio
        - UI
        - World
        - AI
        - Content
        - Platform
        - Multiplayer
        - Testing
        - Documentation
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: dropdown
    id: effort
    attributes:
      label: Estimated Effort
      options:
        - Small (< 1 day)
        - Medium (1-3 days)
        - Large (3-5 days)
        - Extra Large (1-2 weeks)
        - Epic (> 2 weeks)
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: List any tasks or issues this depends on
      placeholder: "Depends on #123, #456"

  - type: textarea
    id: technical
    attributes:
      label: Technical Details
      description: Any technical implementation notes
      placeholder: "Implementation should use..."

  - type: input
    id: assignee
    attributes:
      label: Assignee
      description: Who should work on this? (GitHub username)
      placeholder: "@username"